### ISSUE TITLE
Can't open weather_cityscapes_particles.zip

### ISSUE THREAD

**Issue by shirley-source** [cv-rits/weather-particle-simulator#2]
Sorry to bother you, I encountered a problem when I downloaded  weather_cityscapes_particles.zip and tried to upzip it . It reveals that the archive is corrupt.
I tried for many times and my frenid tried again.The problem was the same. So we think maybe the resource file is wrong.  Can you provide us the weather_cityscapes_particles.zip? Thank you so much~

**Comment by rdecharette** [comment]
Hi. 
Thanks for mentioning this issue. Indeed, weather_cityscapes_particles.zip was corrupted for some unknown reason.
We've fixed the issue (and double checked) you can re-download the valid file.

Best.
