### ISSUE TITLE
Error on Ubuntu20(virtual machine)

### ISSUE THREAD

**Issue by Oleki-xxh** [cv-rits/weather-particle-simulator#3]
Hi
**I am very interested in testing the simulator on my custom images. So I had installed all the dependencies on Ubuntu20(virtual machine), but I met the following error when testing the command "cd lin_x64; ./AHLSimulation".**
“
PARTICLES SIMULATION 12.3

! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! !
Deletion of history may not be working with long delay
be careful of the updatePre
! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! !

[Performance summary]
(!) Using speed up pre-processing
(!) NOT using debugging

Seed: 1298182070
DSD Type 0
DSDP (0) - DSD Type 0
DSDP (0) - Menu:
   0. Quit
   1. Start simulation
   5. Simulation speed (MAX)
Segmentation fault (core dumped)
”

**Then I checked the core file using gdb and got the following message.**

"
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./AHLSimulation...
(No debugging symbols found in ./AHLSimulation)
[New LWP 37834]
[New LWP 37835]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./AHLSimulation'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f9addf13522 in printf_positional (s=s@entry=0x7ffdc633d600, 
    format=format@entry=0x7ffdc633d850 "%02d:%02d:%02d.%0-2147483639d", 
    readonly_format=<optimized out>, readonly_format@entry=0, 
    ap=ap@entry=0x7ffdc633d740, ap_savep=ap_savep@entry=0x7ffdc633d1a8, 
    done=<optimized out>, nspecs_done=<optimized out>, 
--Type <RET> for more, q to quit, c to continue without paging--
    lead_str_end=<optimized out>, work_buffer=<optimized out>, 
    save_errno=<optimized out>, grouping=<optimized out>, 
    thousands_sep=<optimized out>, mode_flags=<optimized out>)
    at vfprintf-internal.c:2016
2016	vfprintf-internal.c: No such file or directory.
[Current thread is 1 (Thread 0x7f9ad92dda80 (LWP 37834))]
(gdb) bt
#0  0x00007f9addf13522 in printf_positional
    (s=s@entry=0x7ffdc633d600, format=format@entry=0x7ffdc633d850 "%02d:%02d:%02d.%0-2147483639d", readonly_format=<optimized out>, 
    readonly_format@entry=0, ap=ap@entry=0x7ffdc633d740, ap_savep=ap_savep@entry=0x7ffdc633d1a8, done=<optimized out>, nspecs_done=<optimized out>, lead_str_end=<optimized out>, work_buffer=<optimized out>, save_errno=<optimized out>, grouping=<optimized out>, thousands_sep=<optimized out>, mode_flags=<optimized out>) at vfprintf-internal.c:2016
#1  0x00007f9addf15f4d in __vfprintf_internal
    (s=s@entry=0x7ffdc633d600, format=format@entry=0x7ffdc633d850 "%02d:%02d:%02d.%0-2147483639d", ap=ap@entry=0x7ffdc633d740, mode_flags=mode_flags@entry=0)
    at vfprintf-internal.c:1733
#2  0x00007f9addf24279 in __vsprintf_internal
    (string=0x7ffdc633ddc0 "00:00:32.\021\220=]U", maxlen=maxlen@entry=18446744073709551615, format=0x7ffdc633d850 "%02d:%02d:%02d.%0-2147483639d", args=args@entry=0x7ffdc633d740, mode_flags=mode_flags@entry=0) at iovsprintf.c:95
#3  0x00007f9addf01048 in __sprintf
    (s=<optimized out>, format=<optimized out>) at sprintf.c:30
#4  0x0000555d3d926a71 in AHLTime2Str(char*, unsigned long) ()
#5  0x0000555d3d90153f in simulationCmd(AHLSimulation*) ()
#6  0x0000555d3d90119a in main ()
"
What should I do to solve the error?

**Comment by rdecharette** [comment]
HI. not so sure to be able to help you there. Looks like a mysterious library compatibility issue. As far as I remember, I ran it on Ubuntu 20 without issues. I'd check all versions of the libs first before investigating further, the virtual machine could be an issue too as particles use GL shader to be rendered. 

Also, I noted you sent another Win10 message so this might be a good direction to avoid the virtual machine.
