### ISSUE TITLE
GLIBC_2.29 dependence on Ubuntu18.04

### ISSUE THREAD

**Issue by fanq15** [cv-rits/weather-particle-simulator#4]
Hi, thanks for your great work!
I am trying to install this repo on Ubuntu18.04, but the dependence is GLIBC_2.29 and Ubuntu18.04 does not support this version.
You said that the code was tested on Ubuntu18.04, so I want to ask for more details about the GLIBC_2.29 dependence.

**Comment by rdecharette** [comment]
Hi, glad the research is helpful.

Looking at the libs dependencies, libm.so.6 is the one requiring GLIBC_2.29. Sorry I cannot provide a helpful solution. In fact, googling GLIBC 2.29 on Ubuntu 18.04, the only _uncertain_ option seems to compile it from source directly:
https://www.linuxfromscratch.org/lfs/view/9.0-systemd/chapter05/glibc.html

let me know if that works.

**Comment by fanq15** [comment]
Thank you for your help!
Actually, I tried to install glibc 2.29 on Ubuntu18.04, but there is always a segmentation core fault bug if I replace the original glibc 2.27 with glibc 2.29.
Do you use docker image to run your code? If so, it is better to upload the docker file for users to install the environment.

**Comment by rdecharette** [comment]
Nope I do not use a docker here. I can add to my todo-list but I don't guarantee this will be anytime soon.

**Comment by fanq15** [comment]
Thanks!
Did you test the code on Ubuntu18.04？

**Comment by rdecharette** [comment]
I recall running my code on 18.04, but I do not recall if it was this version or a former one.

**Comment by fanq15** [comment]
I am sure that the Ubuntu18.04 does not support glibc 2.29.
I installed 2.29 and there are some bugs.
```
 libc-bin : Depends: libc6 (< 2.28) but 2.29-0ubuntu2 is to be installed
 libc-dev-bin : Depends: libc6 (< 2.28) but 2.29-0ubuntu2 is to be installed
                Recommends: manpages but it is not going to be installed
                Recommends: manpages-dev but it is not going to be installed
 libc6 : Breaks: locales (< 2.29) but 2.27-3ubuntu1 is to be installed
         Recommends: libidn2-0 (>= 2.0.5~) but 2.0.4-1.1ubuntu0.2 is to be installed
 libc6-dev : Depends: libc6 (= 2.27-3ubuntu1) but 2.29-0ubuntu2 is to be installed
```

**Comment by fanq15** [comment]
Maybe I need to install Ubuntu20.04 for the code.

**Comment by fanq15** [comment]
```
PARTICLES SIMULATION 12.3

! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! !
Deletion of history may not be working with long delay
be careful of the updatePre
! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! ! !

[Performance summary]
(!) Using speed up pre-processing
(!) NOT using debugging

Seed: 1278851700
DSD Type 0
DSDP (0) - DSD Type 0
DSDP (0) - Menu:
   0. Quit
   1. Start simulation
   5. Simulation speed (MAX)
Segmentation fault (core dumped)
```
Hi, is it a bug?

**Comment by rdecharette** [comment]
Hello,
which ubuntu are you running on (still 18 or 20), is that a virtual machine ?
It seems your error is similar to [this one](https://github.com/cv-rits/weather-particle-simulator/issues/3#issue-1027150365) but frankly I have little cue on it. Apparently it seems to be related to the print command.

**Comment by fanq15** [comment]
Thanks! I think they are the same bug. I use the ubuntu20.04 environment.
I met another osg installation bug and try to solve it.

**Comment by fanq15** [comment]
Does the code need cuda and GPU?

**Comment by rdecharette** [comment]
Cuda is not needed. As the code uses shader functionalities from OpenGL a GPU _might_ be needed.

Is that a virtual environment or a real Ubuntu ?

**Comment by fanq15** [comment]
Mine is the real Ubuntu.

**Comment by fanq15** [comment]
Finally, I successfully installed the environment on Ubuntu20.04.
```
   SPECIAL SIMULATIONS
     101. Multiple simulations
     102. Step by step simulation
     103. Scenarios

What do you want to do ?
0
sh: 1: cls: not found
Program ready to close
Press any key to continue . . .
Press any key to continue . . .
```
But the `sh: 1: cls: not found` seems a bug.

**Comment by rdecharette** [comment]
Great ! That seems to work properly indeed. I'm closing the issue.

**Comment by cjm-cai** [comment]
Hey so what was the solution here? I'm running into the same error on Ubuntu 20.04 as well.
