### ISSUE TITLE
Got Segmentation fault (core dumped) after install all dependence

### ISSUE THREAD

**Issue by wangjiyuan9** [cv-rits/weather-particle-simulator#6]
Dear author：

Thank you for your contribution! I installed the corresponding versions of opencv, boost, and osg according to the prompt on readme, but there are still bugs in the running:

Seed: 220060263
DSD Type 0
DSDP (0) - DSD Type 0
DSDP (0) - Menu:
0. Quit
1. Start simulation
5. Simulation speed (MAX)
**Segmentation fault (core dumped)**

I saw that the previous issue mentioned that Ubuntu 20.04 must be used. Is there no way to use 18.04?

Thank you for your help and time

**Comment by rdecharette** [comment]
Hello @wangjiyuan9,

glad our research seems useful. I just added a binary file for Ubuntu 18.04 in the latest commit in `lin_x64/AHLSimulation_bionic`

I cannot guarantee it fully works as it was compile by another user, but it seems to be ok.
If you intend to use it in the rain-rendering project, don't forget to check the readme part [here](https://github.com/astra-vision/weather-particle-simulator#running-the-simulator)

Hope that will help.
