### ISSUE TITLE
Questions about saving of simulation results

### ISSUE THREAD

**Issue by mgcho0608** [cv-rits/weather-particle-simulator#8]
Hello! 
Following the instructions, I have installed the necessary packages for the simulation according to their versions and confirmed that they run properly. However, even after running the simulation until it stopped and then exiting, the results I wanted were not saved. According to the example files on the rain_rendering git, there should be four .xml files along with the automate_log. Is there something wrong with my simulation settings?

**Comment by rdecharette** [comment]
Hello,

For xml files to be written you need to activate "Output simulation file" (70, in the main menu) and set stats level to "Hierarchy" (72). Files are created at the simulation start, and completed upon exit at the end of the simulation.

But if you seek to simulate one of the preset simulation, you can directly use the "special settings" menu which will set all parameters and files outputs automatically. For example to simulate particles for Kitti sequence 32, from main menu type: 99 > 800032 > 102 > 1.

Best.
